"""Standard Webhooks verification for YOUR server.

Verify the ``webhook-id`` / ``webhook-timestamp`` / ``webhook-signature``
headers GetItDone sends to your endpoint. A byte-for-byte port of the producer,
``packages/api-contracts/src/webhooks/signing.ts`` — proven against signatures
generated by that exact TypeScript code in
``tests/fixtures/webhook_vectors.json``.

**Always verify the RAW request bytes.** Parsing the body and re-serializing it
before verification changes the bytes and rejects genuine deliveries::

    from getitdone_py.webhooks import verify_webhook

    @app.post("/hooks/getitdone")
    async def hook(request):
        raw = await request.body()          # bytes, exactly as received
        result = verify_webhook(
            headers=request.headers, raw_body=raw, secret=os.environ["WHSEC"]
        )
        if not result.valid:
            return Response(status_code=400)
        event = json.loads(raw)             # parse only AFTER verifying

Secret GENERATION stays server-side in the product and is deliberately not
shipped here.
"""

from __future__ import annotations

import base64
import binascii
import hmac
import re
import time
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from hashlib import sha256
from typing import Any, Literal

__all__ = [
    "WEBHOOK_DELIVERY_STATES",
    "WEBHOOK_EVENT_TYPES",
    "WEBHOOK_SIGNATURE_TOLERANCE_SECONDS",
    "WebhookVerificationResult",
    "sign_webhook_payload",
    "verify_webhook",
]

#: A signature outside +/-5 minutes of now is rejected.
WEBHOOK_SIGNATURE_TOLERANCE_SECONDS = 5 * 60

WEBHOOK_SECRET_PREFIX = "whsec_"
SIGNATURE_VERSION = "v1"

#: The frozen subscribable event vocabulary.
WEBHOOK_EVENT_TYPES: tuple[str, ...] = ("task.created", "task.updated", "task.archived")

#: Delivery lifecycle states reported by ``webhook_endpoints.list_deliveries()``.
WEBHOOK_DELIVERY_STATES: tuple[str, ...] = (
    "PENDING",
    "DELIVERING",
    "SUCCEEDED",
    "FAILED",
    "DISABLED",
)

FailureReason = Literal[
    "malformed_signature_header",
    "malformed_timestamp",
    "timestamp_out_of_tolerance",
    "signature_mismatch",
]

_DIGITS = re.compile(r"^\d+$")


@dataclass(frozen=True)
class WebhookVerificationResult:
    """Outcome of :func:`verify_webhook`. Falsy when invalid, so ``if not result:``
    works as well as ``if not result.valid:``."""

    valid: bool
    reason: FailureReason | None = None

    def __bool__(self) -> bool:
        return self.valid


def _secret_key_bytes(secret: str) -> bytes:
    """Derive the HMAC key from a ``whsec_`` secret.

    GOTCHA: strip the prefix, then **base64url**-decode the remainder — the
    producer uses Node's ``base64url``, not the plain base64 the Standard
    Webhooks reference implementation uses. Getting this wrong yields a
    signature mismatch on every genuine delivery.
    """
    material = (
        secret[len(WEBHOOK_SECRET_PREFIX) :] if secret.startswith(WEBHOOK_SECRET_PREFIX) else secret
    )
    padded = material + "=" * (-len(material) % 4)
    return base64.urlsafe_b64decode(padded)


def _compute_signature_base64(
    webhook_id: str, timestamp_seconds: int, raw_body: str, secret: str
) -> str:
    """HMAC-SHA256(key, ``{id}.{timestamp}.{raw_body}``), standard-base64 encoded."""
    signed_content = f"{webhook_id}.{timestamp_seconds}.{raw_body}".encode()
    digest = hmac.new(_secret_key_bytes(secret), signed_content, sha256).digest()
    return base64.b64encode(digest).decode("ascii")


def sign_webhook_payload(
    *,
    webhook_id: str,
    timestamp_seconds: int,
    raw_body: str | bytes,
    secrets: Sequence[str],
) -> dict[str, str]:
    """Build the three Standard Webhooks headers.

    Shipped for TESTING your own handler (and for the cross-language vectors);
    real deliveries are signed server-side.
    """
    body = raw_body.decode("utf-8") if isinstance(raw_body, bytes) else raw_body
    signature = " ".join(
        SIGNATURE_VERSION
        + ","
        + _compute_signature_base64(webhook_id, timestamp_seconds, body, secret)
        for secret in secrets
    )
    return {
        "webhook-id": webhook_id,
        "webhook-timestamp": str(timestamp_seconds),
        "webhook-signature": signature,
    }


def _header_value(headers: Mapping[str, Any] | Any, name: str) -> str | None:
    """Read a header case-insensitively from a mapping or any ``.get()`` object."""
    getter = getattr(headers, "get", None)
    if getter is not None:
        value = getter(name)
        if value is None:
            value = getter(name.title())
        if value is not None:
            return value[0] if isinstance(value, (list, tuple)) else str(value)

    try:
        items = headers.items()
    except AttributeError:
        return None
    for key, value in items:
        if str(key).lower() == name:
            return value[0] if isinstance(value, (list, tuple)) else str(value)
    return None


def verify_webhook(
    *,
    headers: Mapping[str, Any] | Any,
    raw_body: str | bytes,
    secret: str | Iterable[str],
    tolerance_seconds: int = WEBHOOK_SIGNATURE_TOLERANCE_SECONDS,
    now_seconds: int | None = None,
) -> WebhookVerificationResult:
    """Verify an inbound GetItDone webhook.

    :param headers: the inbound request headers (any mapping; names matched
        case-insensitively).
    :param raw_body: the EXACT bytes read off the wire.
    :param secret: the endpoint's ``whsec_`` secret, or several during a
        rotation window — a mid-rotation delivery carries one ``v1,<sig>``
        entry per active secret and any match verifies.
    """
    webhook_id = _header_value(headers, "webhook-id")
    timestamp_header = _header_value(headers, "webhook-timestamp")
    signature_header = _header_value(headers, "webhook-signature")
    if webhook_id is None or timestamp_header is None or signature_header is None:
        return WebhookVerificationResult(False, "malformed_signature_header")

    if not _DIGITS.match(timestamp_header.strip()):
        return WebhookVerificationResult(False, "malformed_timestamp")
    timestamp = int(timestamp_header.strip())

    now = now_seconds if now_seconds is not None else int(time.time())
    if abs(now - timestamp) > tolerance_seconds:
        return WebhookVerificationResult(False, "timestamp_out_of_tolerance")

    provided = [entry for entry in signature_header.strip().split() if entry]
    if not provided:
        return WebhookVerificationResult(False, "malformed_signature_header")

    candidates: list[bytes] = []
    for entry in provided:
        version, separator, encoded = entry.partition(",")
        if not separator or version != SIGNATURE_VERSION or not encoded:
            return WebhookVerificationResult(False, "malformed_signature_header")
        try:
            candidates.append(base64.b64decode(encoded, validate=True))
        except (binascii.Error, ValueError):
            return WebhookVerificationResult(False, "malformed_signature_header")

    body = raw_body.decode("utf-8") if isinstance(raw_body, bytes) else raw_body
    secrets = [secret] if isinstance(secret, str) else list(secret)

    for candidate_secret in secrets:
        try:
            expected = base64.b64decode(
                _compute_signature_base64(webhook_id, timestamp, body, candidate_secret)
            )
        except (binascii.Error, ValueError):
            continue
        for candidate in candidates:
            # Constant-time compare; a length mismatch is public information,
            # not a secret-dependent timing side channel.
            if len(candidate) == len(expected) and hmac.compare_digest(candidate, expected):
                return WebhookVerificationResult(True)

    return WebhookVerificationResult(False, "signature_mismatch")
